### PR TITLE
Styling styling styling

### PR DESCRIPTION
**Pull request by killercup**
bildschirmfoto 2018-02-22 um 18 35 13

- - -

I might've gone a bit overboard with this. Feel free to ignore the last commit!

### CODE REVIEW

**Comment by mgattozzi** [comment]
Like I said in #3 I'm not that good with styling so I'm all for this. Let me just check it out locally and try it out :)

**Comment by killercup** [comment]
DOn't expect anything too fancy. This is by far the most hacked together and ugly CSS I've written in the last three years. But also it took me like 20min and is mostly copypasta.

**Comment by mgattozzi** [comment]
lol I like it but the CSS for the background color only applies to the content class div. If you add it to the body for CSS it should color everything with that old timey yellow rather than there being white and yellow

**Comment by mgattozzi** [comment]
Also the logo looks like this to me which lol
2018-02-22-124605_734x489_scrot

**Comment by killercup** [comment]
Ah shit, seems like it didn't turn the text in paths, I'll fix it

**Comment by mgattozzi** [comment]
You the best thanks! :D

**Comment by mgattozzi** [comment]
So for some reason the html get's the background color but I don't see it showing up for everything else? Not sure why but it looks like some css styling is applying `background-color: #fff` to the body

**Comment by mgattozzi** [comment]
Logo definitely works now though

**Comment by killercup** [comment]
How about now?

I also want to take this moment to thank the author of [SVGOMG!](https://jakearchibald.github.io/svgomg/).

**Comment by mgattozzi** [comment]
Yeaaaaaaaah boy.

**Pull request merged**
